### ISSUE TITLE
Not compatible with semver 3.0.2

### ISSUE THREAD

**Issue by kwint** [caniko/pydantic-numpy#34]
After running a dependency update on my project I was getting this error:

```
    import pydantic_numpy.typing as pnd
../../../.cache/pypoetry/virtualenvs/metal-core-aCGQNnAQ-py3.11/lib/python3.11/site-packages/pydantic_numpy/__init__.py:1: in <module>
    from pydantic_numpy.helper.annotation import np_array_pydantic_annotated_typing
../../../.cache/pypoetry/virtualenvs/metal-core-aCGQNnAQ-py3.11/lib/python3.11/site-packages/pydantic_numpy/helper/annotation.py:12: in <module>
    from pydantic_numpy.helper.validation import (
../../../.cache/pypoetry/virtualenvs/metal-core-aCGQNnAQ-py3.11/lib/python3.11/site-packages/pydantic_numpy/helper/validation.py:10: in <module>
    from pydantic_numpy.model import MultiArrayNumpyFile
../../../.cache/pypoetry/virtualenvs/metal-core-aCGQNnAQ-py3.11/lib/python3.11/site-packages/pydantic_numpy/model.py:13: in <module>
    from pydantic_numpy.util import np_general_all_close
../../../.cache/pypoetry/virtualenvs/metal-core-aCGQNnAQ-py3.11/lib/python3.11/site-packages/pydantic_numpy/util.py:4: in <module>
    from semver import Version
E   ImportError: cannot import name 'Version' from 'semver' (unknown location)
```

with `semver` on `3.0.2`. Downgrading `semver` to `3.0.1` resolves the issue.

Tbh I'm not sure why this issue just came up, both `pydantic-numpy` and `semver` latest release are not super recent. So this might be something else on my side?

**Comment by caniko** [comment]
Can you provide a method for reproducing from a virtualenv, and your Python version?

**Comment by caniko** [comment]
It worked for me:
```shell
 ╰─λ virtualenv venv
created virtual environment CPython3.11.7.final.0-64 in 187ms
  creator CPython3Posix(dest=/data/can/sand/venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/can/.local/share/virtualenv)
    added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

 ╭─can@normandy in /data/can/sand as 🧙 took 345ms
 ╰─λ source venv/bin/activate
venv/bin/activate (line 48): Unsupported use of '='. In fish, please use 'set VIRTUAL_ENV '/data/can/sand/venv''.
VIRTUAL_ENV='/data/can/sand/venv'
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file venv/bin/activate
source: Error while reading file 'venv/bin/activate'

 ╭─can@normandy in /data/can/sand as 🧙 
[🔴] × source venv/bin/activate.fish 

 ╭─can@normandy in /data/can/sand via  v3.11.7 (venv) as 🧙 took 10ms
 ╰─λ pip install semver pydantic-numpy
Collecting semver
  Downloading semver-3.0.2-py3-none-any.whl.metadata (5.0 kB)
Collecting pydantic-numpy
  Downloading pydantic_numpy-4.1.3-py3-none-any.whl.metadata (4.3 kB)
Collecting compress-pickle[lz4] (from pydantic-numpy)
  Downloading compress_pickle-2.1.0-py3-none-any.whl (24 kB)
Collecting numpy>=1.23.0 (from pydantic-numpy)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 4.3 MB/s eta 0:00:00
Collecting pydantic<3.0,>=2.0 (from pydantic-numpy)
  Downloading pydantic-2.6.1-py3-none-any.whl.metadata (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.5/83.5 kB 5.3 MB/s eta 0:00:00
Collecting ruamel-yaml<0.19.0,>=0.18.5 (from pydantic-numpy)
  Downloading ruamel.yaml-0.18.6-py3-none-any.whl.metadata (23 kB)
Collecting annotated-types>=0.4.0 (from pydantic<3.0,>=2.0->pydantic-numpy)
  Downloading annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.16.2 (from pydantic<3.0,>=2.0->pydantic-numpy)
  Downloading pydantic_core-2.16.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)
Collecting typing-extensions>=4.6.1 (from pydantic<3.0,>=2.0->pydantic-numpy)
  Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel-yaml<0.19.0,>=0.18.5->pydantic-numpy)
  Downloading ruamel.yaml.clib-0.2.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl.metadata (2.2 kB)
Collecting lz4 (from compress-pickle[lz4]->pydantic-numpy)
  Downloading lz4-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Downloading semver-3.0.2-py3-none-any.whl (17 kB)
Downloading pydantic_numpy-4.1.3-py3-none-any.whl (17 kB)
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 13.2 MB/s eta 0:00:00
Downloading pydantic-2.6.1-py3-none-any.whl (394 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.8/394.8 kB 12.9 MB/s eta 0:00:00
Downloading pydantic_core-2.16.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 12.5 MB/s eta 0:00:00
Downloading ruamel.yaml-0.18.6-py3-none-any.whl (117 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.8/117.8 kB 16.2 MB/s eta 0:00:00
Downloading annotated_types-0.6.0-py3-none-any.whl (12 kB)
Downloading ruamel.yaml.clib-0.2.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (544 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 544.0/544.0 kB 13.5 MB/s eta 0:00:00
Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Downloading lz4-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 12.3 MB/s eta 0:00:00
Installing collected packages: typing-extensions, semver, ruamel.yaml.clib, numpy, lz4, compress-pickle, annotated-types, ruamel-yaml, pydantic-core, pydantic, pydantic-numpy
Successfully installed annotated-types-0.6.0 compress-pickle-2.1.0 lz4-4.3.3 numpy-1.26.4 pydantic-2.6.1 pydantic-core-2.16.2 pydantic-numpy-4.1.3 ruamel-yaml-0.18.6 ruamel.yaml.clib-0.2.8 semver-3.0.2 typing-extensions-4.9.0

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip

 ╭─can@normandy in /data/can/sand via  v3.11.7 (venv) as 🧙 took 8s
 ╰─λ python
Python 3.11.7 (main, Jan 29 2024, 16:03:57) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import semver
>>> semver.
semver.SEMVER_SPEC_VERSION  semver.cmd_bump(            semver.match(
semver.Version(             semver.cmd_check(           semver.max_ver(
semver.VersionInfo(         semver.cmd_compare(         semver.min_ver(
semver.bump_build(          semver.cmd_nextver(         semver.parse(
semver.bump_major(          semver.compare(             semver.parse_version_info(
semver.bump_minor(          semver.createparser()       semver.process(
semver.bump_patch(          semver.finalize_version(    semver.replace(
semver.bump_prerelease(     semver.format_version(      semver.version
semver.cli                  semver.main(                
>>> semver.Version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Version.__init__() missing 1 required positional argument: 'major'
>>> semver.Version("1.0.0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/can/sand/venv/lib/python3.11/site-packages/semver/version.py", line 125, in __init__
    version_parts = {"major": int(major), "minor": int(minor), "patch": int(patch)}
                              ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '1.0.0'
>>> semver.Version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Version.__init__() missing 1 required positional argument: 'major'
>>> semver.Version(major=1)
Version(major=1, minor=0, patch=0, prerelease=None, build=None)
>>> import pydantic_numpy.typing as pnd
>>>
```

**Comment by kwint** [comment]
I just reinstalled the project from scratch and don't have the issue. No clue what was going before...

Sorry for wasting your time!

**Comment by caniko** [comment]
No worries, just happy to help! :+1:
